version: '3'
services:
  bird:
    build: ./bird
    ports:
      - "4201:4201"
    depends_on:
      - birdimage
    networks:
      - bird-network

  birdimage:
    build: ./birdImage
    ports:
      - "4200:4200"
    networks:
      - bird-network

networks:
  bird-network:
    driver: bridge
